#!/usr/bin/env python
# -*- coding: utf8 -*-
from __future__ import unicode_literals

import os, json


def write_json(path, data):
    with open(path, 'w') as f:
        json.dump(data, f, ensure_ascii=False, encoding="utf-8") 


locales = ['en', 'fr']
data = {}

for locale in locales:
    data[locale] = []
    path = "public/%s" % locale

    for dirname, dirnames, filenames in os.walk(path):
        if dirname == path:
            continue

        index = "%s/index.html" % dirname
        
        with open(index, 'r') as f:
            _id = f.readline()[:-1]
            title = f.readline()[:-1]
            content = f.readlines()

        _id = _id.decode('utf-8')
        title = _id.decode('utf-8')

        content = [c.decode('utf-8') for c in content]
        content = "".join(content)
        content = content.replace("\n", "")

        rule = {
            'id': _id.encode('utf-8'),
            'title': title.encode('utf-8'),
            'content': content.encode('utf-8')
        }

        data[locale].append(rule)

        json_path = "%s/rule.json" % dirname
        write_json(json_path, rule)

    json_path = "public/%s/rules.json" % locale
    write_json(json_path, data[locale])

json_path = "public/rules.json"
write_json(json_path, data)
